<a href="https://colab.research.google.com/github/codingfarm1/studing/blob/main/Pandas_04_%EC%A1%B0%ED%9A%8C%2C%EC%A0%95%EB%A0%AC%2C%EC%A1%B0%EA%B1%B4%ED%95%84%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **4. 조회, 정렬, 조건필터**

- Pandas를 활용하여 타이타닉호 생존자, 사망자 데이터를 분석
- 데이터를 토대로 생존율이 높은 승객, 생존율이 낮은 승객이 누구인지 판단

In [ ]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df = sns.load_dataset("titanic")
df.head()

## **4.1 조회**

###  **head() 앞 부분 / tail() 뒷 부분 조회**

- default 옵션 값으로 5개의 행이 조회
- 괄호 안에 숫자를 넣어 명시적으로 조회하고 싶은 행의 갯수를 지정할 수 있음

In [ ]:
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [ ]:
df.tail(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

### **info()**
- 컬럼별 정보(information)를 보여줌
- 데이터의 갯수, 데이터의 타입(dtype)을 확인할 때 사용함

In [ ]:
df.info()
# dtypes: object (문자열), category (문자열이지만 카테고리화 할 수 있는 칼럼)
# bool, float64, int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

### **value_counts()**
- column 별 값의 분포 확인, **데이터 분포 확인**
- 남자, 여자, 아이의 데이터 분포 확인하고 싶을 때

In [ ]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

### **속성 : Attributes**
- 속성값은 함수형으로 조회하지 않음<br>


#### 자주 활용하는 DataFrame의 속성 값

- ndim : 차원 출력
- shape : (행, 열) 순서로 출력
- index : 기본 설정된 RangeIndex가 출력
- columns : 열 출력
- values : 모든 값 출력 (numpy array 형식으로 출력)
- T(Transpose) : index와 column의 축을 교환

In [ ]:
df.ndim #차원 출력

2

In [ ]:
df.shape #행, 열 출력

(891, 15)

In [ ]:
df.index #행 인덱스 출력 #기본 값인 RangeIndex가 출력됨

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df.columns #열 출력

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.values #모든 값 출력, numpy array 형식으로 출력

array([[0, 3, 'male', ..., 'Southampton', 'no', False],
       [1, 1, 'female', ..., 'Cherbourg', 'yes', False],
       [1, 3, 'female', ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 'female', ..., 'Southampton', 'no', False],
       [1, 1, 'male', ..., 'Cherbourg', 'yes', True],
       [0, 3, 'male', ..., 'Queenstown', 'no', True]], dtype=object)

In [ ]:
df.T #행과 열을 바꿈 # T: 전치(Transpose)는 Index와 Column의 축을 교환함

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
sibsp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q
class,Third,First,Third,First,Third,Third,First,Third,Third,Second,...,Third,Third,Second,Third,Third,Second,First,Third,First,Third
who,man,woman,woman,woman,man,man,man,child,woman,child,...,man,woman,man,man,woman,man,woman,woman,man,man
adult_male,True,False,False,False,True,True,True,False,False,False,...,True,False,True,True,False,True,False,False,True,True
deck,NaN,C,NaN,C,NaN,NaN,E,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,C,NaN
embark_town,Southampton,Cherbourg,Southampton,Southampton,Southampton,Queenstown,Southampton,Southampton,Southampton,Cherbourg,...,Southampton,Southampton,Southampton,Southampton,Queenstown,Southampton,Southampton,Southampton,Cherbourg,Queenstown
alive,no,yes,yes,yes,no,no,no,no,yes,yes,...,no,no,no,no,no,no,yes,no,yes,no
alone,False,False,True,False,True,True,True,False,False,False,...,True,True,True,True,False,True,True,False,True,True

#### **타입 변환(astype)**

- 변수명['칼럼명'].astype('변경할 타입').head()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df['pclass'].astype('int32').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: int32

In [ ]:
df['pclass'].astype('float32').head()

0    3.0
1    1.0
2    3.0
3    1.0
4    3.0
Name: pclass, dtype: float32

In [ ]:
df['pclass'].astype('str').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: object

In [ ]:
df['pclass'].astype('category').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: category
Categories (3, int64): [1, 2, 3]

## **4.2 정렬(sort)**

### **sort_index: index 정렬, 전체 정렬**
- index 기준으로 정렬함 (기본 오름차순 적용)
- 내림차순 정렬 시, ascending=False

In [ ]:
df.sort_index().head(5) #오름차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.sort_index(ascending=False).head(5) #내림차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

### **sort_values: 값에 대한 정렬**

- 값의 기준으로 행을 정렬함
- by = '기준이 되는 행'을 설정함
- by에 2개 이상의 컬럼을 지정하여 정렬할 수 있음
- 오름차순/내림차순을 컬럼 별로 지정할 수 있음

In [ ]:
df.sort_values(by='age').head() #age를 기준으로 오름차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False

In [ ]:
df.sort_values(by='age', ascending=False).head()  #age를 기준으로 내림차순

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
#문자열 컬럼도 오름차순/내림차순이 알파벳 순서로 정렬됨
df.sort_values(by='class', ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
511,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
500,0,3,male,17.0,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
501,0,3,female,21.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,no,True
502,0,3,female,NaN,0,0,7.6292,Q,Third,woman,False,NaN,Queenstown,no,True

In [ ]:
df.sort_values(by=['fare', 'age']).head() #2개 이상의 컬럼을 기준으로 값 정렬 가능

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
302,0,3,male,19.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
271,1,3,male,25.0,0,0,0.0,S,Third,man,True,NaN,Southampton,yes,True
179,0,3,male,36.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
822,0,1,male,38.0,0,0,0.0,S,First,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0,S,First,man,True,A,Southampton,no,True

In [ ]:
df.sort_values(by=['fare', 'age'], ascending=[False, True]).head() #오름차순/내림차순 정렬도 컬럼에 각각 지정 가능

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False

## **4.3 Indexing, Slicing, 조건 필터링**

### **loc - indexing / slicing**
- indexing과 slicing 가능
- slicing은 [시작(포함) : 끝(포함)] 규칙

In [ ]:
df.loc[5, 'class'] #indexing (5행, class열의 값)

'Third'

In [ ]:
df.loc[2:5, ['age', 'fare', 'who']] #fancy indexing (2:5행, age,fare,who열의 값들)

    age     fare    who
2  26.0   7.9250  woman
3  35.0  53.1000  woman
4  35.0   8.0500    man
5   NaN   8.4583    man

In [ ]:
df.loc[2:5, 'age':'who'].head() #slicing

In [ ]:
df.loc[:6, 'class':'deck']

   class    who  adult_male deck
0  Third    man        True  NaN
1  First  woman       False    C
2  Third  woman       False  NaN
3  First  woman       False    C
4  Third    man        True  NaN
5  Third    man        True  NaN
6  First    man        True    E

### **loc - 조건 필터**

boolean index을 만들어 조건에 맞는 데이터만 추출할 수 있음
- 변수명 = (조건)
- 변수명.loc[변수명]

In [ ]:
cond = (df['age'] >= 70) #조건 생성
cond

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [ ]:
df.loc[cond].head() #조건에 맞는 데이터만 추출

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True

### **loc - 다중 조건**

- 다중 조건은 먼저 condition을 정의하고 &와 |연산자로 복합 조건 생성함

In [ ]:
# 조건 1 정의
cond1 = (df['fare'] > 30)

# 조건 2 정의
cond2 = (df['who'] == 'woman')

df.loc[cond1 & cond2].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False

In [ ]:
df.loc[cond1 | cond2].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False

In [ ]:
cond = (df['age'] >= 70)
df.loc[cond, 'age'] # 조건에 맞는 필터 중 나이 컬럼만 가져오기

96     71.0
116    70.5
493    71.0
630    80.0
672    70.0
745    70.0
851    74.0
Name: age, dtype: float64

In [ ]:
df.loc[cond, 'age'] = -1 # 조건에 맞는 필터 중 나이 컬럼만 -1로 변경
df.loc[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,-1.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,-1.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,-1.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,-1.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,-1.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,-1.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
851,0,3,male,-1.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# 30세 이상 남자 승객 조건 필터링
# fare를 많이 낸 순서대로 내림차순 정렬 + 상위 10개 출력
condition1 = (df['age'] >= 30)
condition2 = (df['who'] == 'man')
df.loc[condition1 & condition2].sort_values(by='fare', ascending=False).head(10)

In [ ]:
# 20세 이상 40세 미만, pclass가 1혹은 2등급인 승객
# survived, pclass, age, fare만 나오게 출력
condition1 = (df['age'] >= 20) & (df['age'] < 40)
condition2 = (df['pclass'] < 3)
df.loc[condition1 & condition2, ['survived', 'pclass', 'age', 'fare']].head(10)

In [ ]:
# tips 데이터셋 중 day가 fri, sat만 필터링
# tip이 10달러보다 적게 낸 데이터만 필터링
# total_bill, tip, smoker, time 컬럼만 출
tips.loc[tips['day'].isin(['Fri', 'Sat']) & (tips['tip'] < 10), ['total_bill', 'tip', 'smoker', 'time']].head(10)

### **iloc**
- loc와 유사하지만, **index**만 허용함
- slicing과 indexing 모두 가능

In [ ]:
df.iloc[1,3] #indexing (1행, 3열의 값)

38.0

In [ ]:
df.iloc[[0,3,4], [0,1,5,6]] #Fancy indexing

   survived  pclass  parch   fare
0         0       3      0   7.25
3         1       1      0  53.10
4         0       3      0   8.05

In [ ]:
df.iloc[:3, :5] #slicing #결과 출력 안됨

### **isin**

- 특정 값의 포함 여부는 isin 함수를 통해 비교가 가능함

In [ ]:
sample = pd.DataFrame({'name': ['kim', 'lee', 'park', 'choi'],
                        'age': [24, 27, 34, 19]})
sample

   name  age
0   kim   24
1   lee   27
2  park   34
3  choi   19

In [ ]:
sample['name'].isin(['kim', 'lee'])

0     True
1     True
2    False
3    False
Name: name, dtype: bool

In [ ]:
sample.isin(['kim', 'lee'])

    name    age
0   True  False
1   True  False
2  False  False
3  False  False

loc을 활용한 조건 필터링으로도 찰떡 궁합임

In [ ]:
condition = sample['name'].isin(['kim', 'lee'])
sample.loc[condition] #조건에 맞는 데이터만 추출

  name  age
0  kim   24
1  lee   27